### ISSUE TITLE
can we update emmet to avoid prefixes appearing?

### ISSUE THREAD

**Issue by jt3k** [jsbin/jsbin#3450]
now when I write `trs` and press tab I see the following:
```css
.gg {
  -webkit-transition: prop time;
  -moz-transition: prop time;
  -ms-transition: prop time;
  -o-transition: prop time;
  transition: prop time;
}
```
I would like to avoid the appearance of a bunch of lines.
