### ISSUE TITLE
Phantom Code in Lingering IFrame

### ISSUE THREAD

**Issue by fny** [jsbin/jsbin#878]
Not quite sure how this happened, but somehow an iframe from a previous edit didn't disappear. While bordered div is removed from the code, it still appears in the preview window:

![screen shot 2013-10-09 at 5 10 23 pm](https://f.cloud.github.com/assets/346068/1301852/235ccf8a-3129-11e3-8fbc-1f2be01dba1a.png)

The previous edit is hiding inside of a lingering iframe which should have been replaced after the update: 

![screen shot 2013-10-09 at 5 10 35 pm](https://f.cloud.github.com/assets/346068/1301811/54c2fa00-3128-11e3-8a00-ea0510d72c30.png)

The bin is at http://jsbin.com/ajEpILi/, but I can't seem to recreate the issue.
### Code Before

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>CSS Pulsator</title>
        <link rel="stylesheet" type="text/css" href="style.css" />
    </head>
    <body>
        <div id="pulsor">Golden Ticket!</div>
    </body>
</html>
```

``` css
#pulsor {
    width: 120px;
    margin: 64px;
    padding: 16px 32px;
    font-size: 32px;
    cursor: auto;
    border-radius: 8px;
    box-shadow: 0 0 10px #333;
}
#pulsor {
    -webkit-animation: pusate 1s infinite alternate;
    -moz-animation: pusate 1s infinite alternate;
    -animation: pusate 1s infinite alternate;
    text-shadow: 0 0 8px #ccc;
}
@-webkit-keyframes pusate {
    from { box-shadow: 0 0 10px #333; }
    to { box-shadow: 0 0 20px #c00; }
}
@-moz-keyframes pusate {
    from { box-shadow: 0 0 10px #333; }
    to { box-shadow: 0 0 20px #c00; }
}
@keyframes pusate {
    from { box-shadow: 0 0 10px #333; }
    to { box-shadow: 0 0 20px #c00; }
}
```
### Code After

``` html
<!DOCTYPE html>
<html>
  <title>Pulsing Div</title>
    <head>
        <title>CSS Pulsator</title>
        <link rel="stylesheet" type="text/css" href="style.css" />
    </head>
    <body>
      <div class="golden-ticket">

        What...?
      </div>

    </body>
</html>
```

The CSS was unchanged.
